export const NAV_ITEMS = [
  { label: "Início", path: "/" },
  { label: "Sobre", path: "/sobre" },
  { label: "Projetos", path: "/projetos" },
  { label: "Publicações", path: "/publicacoes" },
  { label: "Estatísticas", path: "/estatisticas" },
  { label: "Parcerias", path: "/parcerias" },
  { label: "Serviços", path: "/servicos" },
  { label: "Cursos", path: "/cursos" },
  { label: "Formação Complementar", path: "/formacao-complementar" },
  { label: "Eventos", path: "/eventos" },
  { label: "Oportunidades", path: "/oportunidades" },
  { label: "Membros", path: "/membros" },
  { label: "Contato", path: "/contato" },
] as const
